languageCode = "ja"
languageName = "日本語"
weight = 1
title = "RakuBlog"
hasCJKLanguage = true


[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006/1/2"
  logo = "img/logo-square.png"
  # secondaryLogo = "PATH"
  description = "ヴィッセルサポIT屋のなんでもブログ"
  copyright = "&copy; 2019 -{ year }, Rakuichi - All Rights Reserved"



[params.author]
  name = "Rakuichi"
  image = "img/avatar.jpg"
  headline = "ヴィッセルサポIT屋のなんでもブログ"
  bio = "ヴィッセルサポのIT屋"
  links = [
    { x-twitter = "https://twitter.com/rararakuichi" },
    { github = "https://github.com/rakuichi4817" },
  ]
